/**:
  ros__parameters:
    cmd_vel_stamped: false

    linear_velocity_factor:
      fast: 1.0
      regular: 1.0
      slow: 0.2

    angular_velocity_factor:
      fast: 1.0
      regular: 1.0
      slow: 0.2

    input_index_map:
      axis:
        angular_z: "A0"       # right joystick X (rotation / yaw)
        linear_x: "A4"        # left joystick Y (forward / backward)
        linear_y: "A3"        # left joystick X (left / right)
        linear_z_up: "A1"     # left joystick Y (up / down)
      dead_man_switch: "B4"   # L1
